from django.urls import path
from . import views

urlpatterns = [
    path('empleados/', views.lista_empleados, name='lista_empleados'),
    path('empleados/crear/', views.crear_empleado_ajax, name='crear_empleado_ajax'),
    path('empleados/obtener/<int:id>/', views.obtener_empleado_json, name='obtener_empleado_json'),
    path('empleados/editar/<int:id>/', views.editar_empleado_ajax, name='editar_empleado_ajax'),
    path('contratos/', views.lista_contratos, name='lista_contratos'),
    path('contratos/crear/', views.crear_contrato_ajax, name='crear_contrato_ajax'),
    path('contratos/obtener/<int:id>/', views.obtener_contrato_json, name='obtener_contrato_json'),
    path('contratos/editar/<int:id>/', views.editar_contrato_ajax, name='editar_contrato_ajax'),
    path('contratos/eliminar/<int:id>/', views.eliminar_contrato_ajax, name='eliminar_contrato_ajax'),
    path('contratistas/', views.lista_contratistas, name='lista_contratistas'),
    path('contratistas/crear/', views.crear_contratista_ajax, name='crear_contratista_ajax'),
    path('contratistas/obtener/<int:id>/', views.obtener_contratista_json, name='obtener_contratista_json'),
    path('contratistas/editar/<int:id>/', views.editar_contratista_ajax, name='editar_contratista_ajax'),
    path('contratistas/exportar-sisub/<int:id>/', views.exportar_sisub_contratos, name='exportar_sisub_contratos'),
    path('contratistas/exportar-sisub-trabajadores/<int:id>/', views.exportar_sisub_trabajadores, name='exportar_sisub_trabajadores'),
    path('contratistas/exportar-icsoe/<int:id>/', views.exportar_icsoe, name='exportar_icsoe'),
    path('beneficiarios/', views.lista_beneficiarios, name='lista_beneficiarios'),
    path('beneficiarios/crear/', views.crear_beneficiario_ajax, name='crear_beneficiario_ajax'),
    path('beneficiarios/obtener/<int:id>/', views.obtener_beneficiario_json, name='obtener_beneficiario_json'),
    path('beneficiarios/editar/<int:id>/', views.editar_beneficiario_ajax, name='editar_beneficiario_ajax'),
    path('sua/', views.lista_sua, name='lista_sua'),
    path('sua/importar/', views.importar_sua_ajax, name='importar_sua_ajax'),
    path('sua/obtener/<int:id>/', views.obtener_registro_sua_json, name='obtener_registro_sua_json'),
    path('sua/eliminar/<int:id>/', views.eliminar_sua_ajax, name='eliminar_sua_ajax'),
    path('sua/exportar/<int:id>/', views.exportar_sua_excel, name='exportar_sua_excel'),
    path('sua/alta-empleados/<int:id>/', views.alta_empleados_sua_ajax, name='alta_empleados_sua_ajax'),
    path('nomina/', views.lista_nomina, name='lista_nomina'),
    path('nomina/crear/', views.crear_nomina_ajax, name='crear_nomina_ajax'),
    path('nomina/obtener/<int:id>/', views.obtener_nomina_json, name='obtener_nomina_json'),
    path('nomina/editar/<int:id>/', views.editar_nomina_ajax, name='editar_nomina_ajax'),
    path('nomina/eliminar/<int:id>/', views.eliminar_nomina_ajax, name='eliminar_nomina_ajax'),
    path('nomina/importar/', views.importar_nomina_ajax, name='importar_nomina_ajax'),
]
