from django.urls import path
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='lista_empleados', permanent=False)),
    path('empleados/', views.lista_empleados, name='lista_empleados'),
    path('empleados/crear/', views.crear_empleado_ajax, name='crear_empleado_ajax'),
    path('empleados/obtener/<int:id>/', views.obtener_empleado_json, name='obtener_empleado_json'),
    path('empleados/editar/<int:id>/', views.editar_empleado_ajax, name='editar_empleado_ajax'),
    path('empleados/eliminar/<int:id>/', views.eliminar_empleado_ajax, name='eliminar_empleado_ajax'),
    path('contratos/', views.lista_contratos, name='lista_contratos'),
    path('contratos/crear/', views.crear_contrato_ajax, name='crear_contrato_ajax'),
    path('contratos/obtener/<int:id>/', views.obtener_contrato_json, name='obtener_contrato_json'),
    path('contratos/preparar-siguiente-version/<int:id>/', views.preparar_siguiente_version_contrato_json, name='preparar_siguiente_version_contrato_json'),
    path('contratos/editar/<int:id>/', views.editar_contrato_ajax, name='editar_contrato_ajax'),
    path('contratos/eliminar/<int:id>/', views.eliminar_contrato_ajax, name='eliminar_contrato_ajax'),
    path('contratos/importar/', views.importar_contratos_ajax, name='importar_contratos_ajax'),
    path('contratistas/', views.lista_contratistas, name='lista_contratistas'),
    path('contratistas/crear/', views.crear_contratista_ajax, name='crear_contratista_ajax'),
    path('contratistas/obtener/<int:id>/', views.obtener_contratista_json, name='obtener_contratista_json'),
    path('contratistas/editar/<int:id>/', views.editar_contratista_ajax, name='editar_contratista_ajax'),
    path('contratistas/eliminar/<int:id>/', views.eliminar_contratista_ajax, name='eliminar_contratista_ajax'),
    path('contratistas/importar/', views.importar_contratistas_ajax, name='importar_contratistas_ajax'),
    path('contratistas/obtener-beneficiarios/<int:id>/', views.obtener_beneficiarios_contratista_json, name='obtener_beneficiarios_contratista_json'),
    path('contratistas/exportar-sisub/<int:id>/', views.exportar_sisub_contratos, name='exportar_sisub_contratos'),
    path('contratistas/exportar-sisub-trabajadores/<int:id>/', views.exportar_sisub_trabajadores, name='exportar_sisub_trabajadores'),
    path('contratistas/exportar-carga-trabajadores/<int:id>/', views.exportar_carga_trabajadores, name='exportar_carga_trabajadores'),
    path('contratistas/exportar-icsoe/<int:id>/', views.exportar_icsoe, name='exportar_icsoe'),
    path('contratistas/probar-smtp/', views.api_probar_contratista_smtp, name='api_probar_contratista_smtp'),
    path('beneficiarios/', views.lista_beneficiarios, name='lista_beneficiarios'),
    path('beneficiarios/crear/', views.crear_beneficiario_ajax, name='crear_beneficiario_ajax'),
    path('beneficiarios/obtener/<int:id>/', views.obtener_beneficiario_json, name='obtener_beneficiario_json'),
    path('beneficiarios/editar/<int:id>/', views.editar_beneficiario_ajax, name='editar_beneficiario_ajax'),
    path('beneficiarios/eliminar/<int:id>/', views.eliminar_beneficiario_ajax, name='eliminar_beneficiario_ajax'),
    path('beneficiarios/portal/', views.portal_beneficiarios, name='portal_beneficiarios'),
    path('beneficiarios/documentacion/obtener/<int:id>/', views.obtener_documentacion_json, name='obtener_documentacion_json'),
    path('beneficiarios/documentacion/subir/<int:id>/', views.subir_documento_ajax, name='subir_documento_ajax'),
    path('beneficiarios/documentacion/eliminar/<int:id>/', views.eliminar_documento_ajax, name='eliminar_documento_ajax'),
    path('beneficiarios/documentacion/descargar/<int:doc_id>/', views.descargar_documento_beneficiario, name='descargar_documento_beneficiario'),
    path('beneficiarios/documentacion/cambiar-estatus/<int:doc_id>/', views.cambiar_estatus_documento_ajax, name='cambiar_estatus_documento_ajax'),
    path('sua/', views.lista_sua, name='lista_sua'),
    path('sua/importar/', views.importar_sua_ajax, name='importar_sua_ajax'),
    path('sua/obtener/<int:id>/', views.obtener_registro_sua_json, name='obtener_registro_sua_json'),
    path('sua/eliminar/<int:id>/', views.eliminar_sua_ajax, name='eliminar_sua_ajax'),
    path('sua/exportar/<int:id>/', views.exportar_sua_excel, name='exportar_sua_excel'),
    path('sua/alta-empleados/<int:id>/', views.alta_empleados_sua_ajax, name='alta_empleados_sua_ajax'),
    path('sua/alta-empleados-cargador/<int:id>/', views.alta_empleados_cargador_sua_ajax, name='alta_empleados_cargador_sua_ajax'),
    path('sua/descargar-plantilla-cargador/', views.descargar_plantilla_cargador_sua, name='descargar_plantilla_cargador_sua'),
    path('nomina/', views.lista_nomina, name='lista_nomina'),
    path('nomina/crear/', views.crear_nomina_ajax, name='crear_nomina_ajax'),
    path('nomina/obtener/<int:id>/', views.obtener_nomina_json, name='obtener_nomina_json'),
    path('nomina/editar/<int:id>/', views.editar_nomina_ajax, name='editar_nomina_ajax'),
    path('nomina/eliminar/<int:id>/', views.eliminar_nomina_ajax, name='eliminar_nomina_ajax'),
    path('nomina/importar/', views.importar_nomina_ajax, name='importar_nomina_ajax'),
    path('nomina/actualizar-trabajadores/', views.actualizar_datos_trabajadores_nomina_ajax, name='actualizar_datos_trabajadores_nomina_ajax'),
    path('nomina/exportar-excel/', views.exportar_nominas_excel, name='exportar_nominas_excel'),
    
    # Rutas para integración SAT XML
    path('sat/solicitar/', views.solicitar_descarga_sat_ajax, name='solicitar_descarga_sat_ajax'),
    path('sat/diagnostico/', views.diagnostico_fiel_ajax, name='diagnostico_fiel_ajax'),
    path('sat/verificar-fiel/<int:contratista_id>/', views.verificar_fiel_contratista_ajax, name='verificar_fiel_contratista_ajax'),
    path('sat/verificar-estatus/<int:solicitud_id>/', views.verificar_estatus_sat_ajax, name='verificar_estatus_sat_ajax'),
    path('sat/solicitudes/lista/', views.listar_solicitudes_sat_ajax, name='listar_solicitudes_sat_ajax'),
    path('sat/integrar/<int:solicitud_id>/', views.integrar_xml_sat_ajax, name='integrar_xml_sat_ajax'),
    path('sat/cargar-xml/', views.cargar_xml_directo_ajax, name='cargar_xml_directo_ajax'),

    # Rutas para Proveedores (Recursos Humanos)
    path('proveedores/crear/', views.crear_proveedor_rh_ajax, name='crear_proveedor_rh_ajax'),
    path('proveedores/obtener/<int:id>/', views.obtener_proveedor_rh_json, name='obtener_proveedor_rh_json'),
    path('proveedores/editar/<int:id>/', views.editar_proveedor_rh_ajax, name='editar_proveedor_rh_ajax'),
    path('proveedores/eliminar/<int:id>/', views.eliminar_proveedor_rh_ajax, name='eliminar_proveedor_rh_ajax'),
    
    path('proveedores/portal/', views.portal_proveedores, name='portal_proveedores'),
    path('proveedores/documentacion/obtener/<int:id>/', views.obtener_documentacion_proveedor_json, name='obtener_documentacion_proveedor_json'),
    path('proveedores/documentacion/subir/<int:id>/', views.subir_documento_proveedor_ajax, name='subir_documento_proveedor_ajax'),
    path('proveedores/documentacion/eliminar/<int:id>/', views.eliminar_documento_proveedor_ajax, name='eliminar_documento_proveedor_ajax'),
    path('proveedores/documentacion/descargar/<int:doc_id>/', views.descargar_documento_proveedor, name='descargar_documento_proveedor'),
    path('proveedores/documentacion/cambiar-estatus/<int:doc_id>/', views.cambiar_estatus_documento_proveedor_ajax, name='cambiar_estatus_documento_proveedor_ajax'),
    path('proveedores/descargar-plantilla-trabajadores/', views.descargar_plantilla_reporte_trabajadores, name='descargar_plantilla_reporte_trabajadores'),
]
