# Generated by Django 6.0.2 on 2026-03-06 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('cotizaciones', '0001_initial'),
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizaciones.cotizacion', verbose_name='Cotización Relacionada'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa (Tenant)'),
        ),
    ]
