version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles   # bind mount (carpeta real)
      - ./media:/app/media               # bind mount (carpeta real)
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=sistema_inventario.settings
    command: gunicorn sistema_inventario.wsgi:application --bind 0.0.0.0:8000
    restart: unless-stopped

# Eliminamos o comentamos la sección volumes (ya no la necesitamos)
# volumes:
#   static_volume:
#   media_volume: