# Generated by Django 6.0.2 on 2026-03-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_abastecimiento',
            field=models.CharField(choices=[('stock', 'Stock'), ('produccion', 'Producción'), ('compra', 'Compra')], default='compra', max_length=20, verbose_name='Tipo de Abastecimiento'),
        ),
    ]
