# Generated by Django 6.0.2 on 2026-03-12 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_tipo_abastecimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio')], default='producto', max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad Requerida')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en', to='core.producto', verbose_name='Componente')),
                ('producto_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='core.producto', verbose_name='Producto Final (Ensamblado)')),
            ],
            options={
                'unique_together': {('producto_padre', 'componente')},
            },
        ),
    ]
