# Generated by Django 6.0.2 on 2026-03-13 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_tipo_detallereceta'),
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_core', to='panel.empresa', verbose_name='Empresa (Tenant)'),
        ),
    ]
