# Generated by Django 6.0.2 on 2026-03-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_categoria_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costos_lista',
            field=models.JSONField(blank=True, default=list, verbose_name='Lista de Costos Extra'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precios_lista',
            field=models.JSONField(blank=True, default=list, verbose_name='Lista de Precios Extra'),
        ),
    ]
