# Generated by Django 6.0.2 on 2026-03-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_costos_lista_producto_precios_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ieps',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Impuesto Especial sobre Producción y Servicios', max_digits=5, verbose_name='IEPS (%)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Impuesto al Valor Agregado', max_digits=5, verbose_name='IVA (%)'),
        ),
    ]
