# Generated by Django 6.0.2 on 2026-03-29 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_producto_ieps_producto_iva'),
        ('produccion', '0003_test_itemtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='test_calidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produccion.test', verbose_name='Test de Calidad'),
        ),
    ]
