# Generated by Django 6.0.2 on 2026-05-12 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_producto_sucursal_alter_producto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='sucursal',
        ),
    ]
