# Generated by Django 6.0.2 on 2026-05-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_producto_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='clave',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave'),
        ),
    ]
