# Generated by Django 6.0.2 on 2026-05-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_producto_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tiene_iva',
            field=models.BooleanField(default=True, verbose_name='Tiene IVA'),
        ),
    ]
