# Generated by Django 6.0.2 on 2026-05-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_producto_tiene_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ieps',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Impuesto Especial sobre Producción y Servicios', max_digits=5, verbose_name='IEPS (%)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Impuesto al Valor Agregado', max_digits=5, verbose_name='IVA (%)'),
        ),
    ]
