# Generated by Django 6.0.2 on 2026-05-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_producto_ieps_alter_producto_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('H87', 'H87 (Pieza)'), ('E48', 'E48 (Unidad de servicio)')], default='H87', max_length=50, verbose_name='Unidad de Medida'),
        ),
    ]
