# Generated by Django 6.0.2 on 2026-06-05 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_producto_unidad_medida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='extras_data',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Datos Extras (Lotes/Series)'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='quitar_reserva',
            field=models.IntegerField(default=0, verbose_name='Quitar Reserva'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serie'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('ajuste', 'Ajuste'), ('produccion', 'Producción')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
