# Generated by Django 5.2.15 on 2026-07-03 18:10

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_categoria_id_alter_detallereceta_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to_producto_imagen, verbose_name='Imagen'),
        ),
    ]
