# Generated by Django 5.2.15 on 2026-07-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallereceta',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=12, verbose_name='Cantidad Requerida'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('H87', 'H87 (Pieza)'), ('E48', 'E48 (Unidad de servicio)'), ('KGM', 'KGM (Kilogramo)'), ('GRM', 'GRM (Gramo)'), ('LTR', 'LTR (Litro)'), ('MLT', 'MLT (Mililitro)'), ('MTR', 'MTR (Metro)')], default='H87', max_length=50, verbose_name='Unidad de Medida'),
        ),
    ]
