# Generated by Django 5.2.15 on 2026-07-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_detallereceta_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='mostrar_en_pos',
            field=models.BooleanField(default=True, verbose_name='Mostrar en POS'),
        ),
    ]
