# Generated by Django 5.2.15 on 2026-07-08 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_producto_mostrar_en_pos'),
        ('panel', '0011_empresa_modulo_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificadorProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permite_extra', models.BooleanField(default=True, verbose_name='Permite Extra (+)')),
                ('permite_sin', models.BooleanField(default=True, verbose_name='Permite Sin (-)')),
                ('precio_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio Extra')),
                ('cantidad_modificadora', models.DecimalField(decimal_places=4, default=1.0, max_digits=12, verbose_name='Cantidad Modificadora')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
                ('producto_modificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificadores_asociados', to='core.producto', verbose_name='Producto Modificador')),
                ('producto_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificadores', to='core.producto', verbose_name='Producto Principal')),
            ],
            options={
                'verbose_name': 'Modificador de Producto',
                'verbose_name_plural': 'Modificadores de Productos',
                'unique_together': {('producto_padre', 'producto_modificador')},
            },
        ),
    ]
