# Generated by Django 5.2.15 on 2026-07-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_modificadorproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='permitir_modificadores',
            field=models.BooleanField(default=False, verbose_name='Permitir Modificadores'),
        ),
    ]
