# Generated by Django 5.2.15 on 2026-07-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_producto_permitir_modificadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='maneja_caducidad',
            field=models.BooleanField(default=False, verbose_name='Maneja Caducidad'),
        ),
    ]
