# Generated by Django 5.2.15 on 2026-08-01 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_producto_maneja_caducidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoBarrasAdicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código de Barras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='core.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Código de Barras Adicional',
                'verbose_name_plural': 'Códigos de Barras Adicionales',
            },
        ),
    ]
