# Generated by Django 6.0.2 on 2026-05-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='activo',
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido_materno',
            field=models.CharField(default='', max_length=100, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=100, verbose_name='Apellido Paterno'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='banco_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='caja_ahorro',
            field=models.BooleanField(default=False, verbose_name='Caja de Ahorro'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='calle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ciudad',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='clabe',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CLABE'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='clave_percepcion_sat',
            field=models.CharField(default='001', max_length=10, verbose_name='Clave Percepción SAT'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='colonia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='correo_personal',
            field=models.EmailField(default='', max_length=254, verbose_name='Correo Personal'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='curp',
            field=models.CharField(default='', max_length=18, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(default='', max_length=100, verbose_name='Departamento/Área'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido'), ('baja_temporal', 'Baja Temporal'), ('baja_definitiva', 'Baja Definitiva')], default='activo', max_length=20, verbose_name='Estado del Empleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado_civil',
            field=models.CharField(choices=[('soltero', 'Soltero(a)'), ('casado', 'Casado(a)'), ('union_libre', 'Unión Libre'), ('divorciado', 'Divorciado(a)'), ('viudo', 'Viudo(a)')], default='soltero', max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado_dir',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_antiguedad',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Antigüedad'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_expiracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Expiración Contrato'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fondo_ahorro',
            field=models.BooleanField(default=False, verbose_name='Fondo de Ahorro'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='forma_pago',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='quincenal', max_length=20, verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='genero',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('NB', 'No binario')], default='H', max_length=5, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_oficial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Oficial (INE/Pasaporte)'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='jornada',
            field=models.CharField(choices=[('diurna', 'Diurna'), ('nocturna', 'Nocturna'), ('mixta', 'Mixta'), ('parcial', 'Tiempo Parcial')], default='diurna', max_length=20, verbose_name='Jornada'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='motivo_baja',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo de Baja'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nacionalidad',
            field=models.CharField(default='Mexicana', max_length=100, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nss',
            field=models.CharField(default='', max_length=11, verbose_name='NSS'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='num_cuenta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Cuenta'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='num_empleado',
            field=models.CharField(default='', max_length=20, verbose_name='Número de Empleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='num_ext',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Exterior'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='num_fonacot',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número FONACOT'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='num_infonavit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Infonavit'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='num_int',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Interior'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='num_tarjeta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Tarjeta'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='porcentaje_fondo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje Fondo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='registro_patronal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registro Patronal IMSS'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rfc',
            field=models.CharField(default='', max_length=13, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='riesgo_trabajo',
            field=models.CharField(choices=[('I', 'Clase I'), ('II', 'Clase II'), ('III', 'Clase III'), ('IV', 'Clase IV'), ('V', 'Clase V')], default='I', max_length=5, verbose_name='Riesgo de Trabajo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='salario_diario_ordinario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salario Diario Ordinario'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sbc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salario Base de Cotización'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sdi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salario Diario Integrado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='supervisor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Supervisor Inmediato'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tarjeta_nomina',
            field=models.BooleanField(default=False, verbose_name='Tarjeta de Nómina'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Fijo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono_movil',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono Móvil'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_contrato',
            field=models.CharField(choices=[('indefinido', 'Indefinido'), ('temporal_obra', 'Temporal por obra'), ('temporal_tiempo', 'Temporal por tiempo determinado')], default='indefinido', max_length=20, verbose_name='Tipo de Contrato'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_cuenta',
            field=models.CharField(choices=[('ahorro', 'Ahorro'), ('cheques', 'Cheques'), ('tarjeta', 'Tarjeta')], default='tarjeta', max_length=20, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_salario',
            field=models.CharField(choices=[('fijo', 'Fijo'), ('variable', 'Variable'), ('mixto', 'Mixto')], default='fijo', max_length=20, verbose_name='Tipo de Salario'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_trabajador',
            field=models.CharField(choices=[('base', 'Base'), ('eventual', 'Eventual'), ('confianza', 'Confianza'), ('sindicalizado', 'Sindicalizado')], default='base', max_length=20, verbose_name='Tipo de Trabajador'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='unidad_monetaria',
            field=models.CharField(default='MXN', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(default='', max_length=100, verbose_name='Puesto'),
        ),
    ]
