# Generated by Django 6.0.2 on 2026-05-13 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_empresa_modulo_recursos_humanos'),
        ('recursos_humanos', '0003_empleado_sucursal_alter_empleado_fecha_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Indefinido'), ('temporal_obra', 'Temporal por obra'), ('temporal_tiempo', 'Temporal por tiempo determinado')], default='indefinido', max_length=20, verbose_name='Tipo de Contrato')),
                ('sueldo_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sueldo Mensual')),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], default='vigente', max_length=20, verbose_name='Estado')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Archivo del Contrato')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas/Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='recursos_humanos.empleado', verbose_name='Empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
