# Generated by Django 6.0.2 on 2026-05-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0004_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='sueldo_mensual',
        ),
        migrations.AddField(
            model_name='contrato',
            name='contratante',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Contratante'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empleados',
            field=models.ManyToManyField(related_name='contratos_asignados', to='recursos_humanos.empleado', verbose_name='Colaboradores'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='folio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Folio de Contrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='monto_contrato',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto del Contrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='num_estimado_trabajadores',
            field=models.IntegerField(default=0, verbose_name='Número Estimado de Trabajadores'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='objeto_contrato',
            field=models.TextField(blank=True, null=True, verbose_name='Objeto del Contrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='organizacion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Término'),
        ),
    ]
