# Generated by Django 6.0.2 on 2026-05-13 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0005_remove_contrato_empleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='archivo',
        ),
    ]
