# Generated by Django 6.0.2 on 2026-05-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0006_remove_contrato_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='vigencia_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Vigencia de Contrato'),
        ),
    ]
