# Generated by Django 6.0.2 on 2026-05-13 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0008_contratista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='organizacion',
        ),
        migrations.AddField(
            model_name='contrato',
            name='contratista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.contratista', verbose_name='Contratista'),
        ),
    ]
