# Generated by Django 6.0.2 on 2026-05-13 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_empresa_modulo_recursos_humanos'),
        ('recursos_humanos', '0009_remove_contrato_organizacion_contrato_contratista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('nombre_razon_social', models.CharField(max_length=200, verbose_name='Nombre / Razón Social')),
                ('registro_patronal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Registro Patronal')),
                ('calle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Calle')),
                ('num_ext', models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. Ext.')),
                ('num_int', models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. Int.')),
                ('entre_calle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Entre calle')),
                ('y_calle', models.CharField(blank=True, max_length=150, null=True, verbose_name='y calle')),
                ('colonia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Colonia')),
                ('cp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('municipio_alcaldia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Municipio o Alcaldía')),
                ('entidad_federativa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entidad Federativa')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
            },
        ),
    ]
