# Generated by Django 6.0.2 on 2026-05-14 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0010_beneficiario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='contratante',
        ),
        migrations.AddField(
            model_name='contrato',
            name='beneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.beneficiario', verbose_name='Beneficiario'),
        ),
    ]
