# Generated by Django 6.0.2 on 2026-05-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0011_remove_contrato_contratante_contrato_beneficiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='clave_percepcion_sat',
            field=models.CharField(default='001', max_length=100, verbose_name='Clave Percepción SAT'),
        ),
    ]
