# Generated by Django 6.0.2 on 2026-05-14 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferencias', '0006_sucursal'),
        ('recursos_humanos', '0012_alter_empleado_clave_percepcion_sat'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='contratista',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.sucursal', verbose_name='Sucursal'),
        ),
    ]
