# Generated by Django 6.0.2 on 2026-05-14 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_empresa_modulo_recursos_humanos'),
        ('preferencias', '0006_sucursal'),
        ('recursos_humanos', '0013_beneficiario_sucursal_contratista_sucursal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSUA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nss', models.CharField(max_length=15, verbose_name='NSS')),
                ('nombre_trabajador', models.CharField(max_length=255, verbose_name='Nombre del Trabajador')),
                ('dias_cotizados', models.IntegerField(default=0, verbose_name='Días Cotizados')),
                ('sdi', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='SDI')),
                ('cuota_fija', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('excedente_smg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prestaciones_dinero', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gastos_medicos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('riesgo_trabajo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invalidez_vida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('guarderias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retiro', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cesantia_vejez', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('infonavit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('periodo', models.CharField(max_length=50, verbose_name='Periodo (Mes/Año)')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Registro SUA',
                'verbose_name_plural': 'Registros SUA',
            },
        ),
    ]
