# Generated by Django 6.0.2 on 2026-05-14 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_empresa_modulo_recursos_humanos'),
        ('preferencias', '0006_sucursal'),
        ('recursos_humanos', '0014_registrosua'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionSUA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_patronal', models.CharField(blank=True, max_length=50, null=True)),
                ('rfc_empresa', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True)),
                ('cp', models.CharField(blank=True, max_length=10, null=True)),
                ('entidad', models.CharField(blank=True, max_length=100, null=True)),
                ('area_geografica', models.CharField(blank=True, max_length=10, null=True)),
                ('delegacion_imss', models.CharField(blank=True, max_length=150, null=True)),
                ('subdelegacion_imss', models.CharField(blank=True, max_length=150, null=True)),
                ('municipio_alcaldia', models.CharField(blank=True, max_length=150, null=True)),
                ('prima_rt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Aportación Patronal / Prima RT')),
                ('periodo', models.CharField(max_length=50, verbose_name='Periodo del Reporte')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Importación SUA',
                'verbose_name_plural': 'Importaciones SUA',
            },
        ),
        migrations.CreateModel(
            name='TrabajadorSUA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nss', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('rfc_curp', models.CharField(blank=True, max_length=50, null=True)),
                ('clave_ubicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('clave_mov', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_mov', models.CharField(blank=True, max_length=20, null=True)),
                ('dias', models.IntegerField(default=0)),
                ('sdi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('patronal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('obrera', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('baja_fecha', models.CharField(blank=True, max_length=20, null=True)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='recursos_humanos.importacionsua')),
            ],
            options={
                'verbose_name': 'Trabajador SUA',
                'verbose_name_plural': 'Trabajadores SUA',
            },
        ),
        migrations.DeleteModel(
            name='RegistroSUA',
        ),
    ]
