# Generated by Django 6.0.2 on 2026-05-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0015_importacionsua_trabajadorsua_delete_registrosua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacionsua',
            name='actividad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importacionsua',
            name='area_geografica',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='importacionsua',
            name='cp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='importacionsua',
            name='delegacion_imss',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importacionsua',
            name='domicilio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importacionsua',
            name='entidad',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='importacionsua',
            name='municipio_alcaldia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importacionsua',
            name='nombre_razon_social',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importacionsua',
            name='prima_rt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aportación Patronal / Prima RT'),
        ),
        migrations.AlterField(
            model_name='importacionsua',
            name='registro_patronal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importacionsua',
            name='rfc_empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='importacionsua',
            name='subdelegacion_imss',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
