# Generated by Django 6.0.2 on 2026-05-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0016_alter_importacionsua_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacionsua',
            name='area_geografica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importacionsua',
            name='cp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='importacionsua',
            name='delegacion_imss',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importacionsua',
            name='entidad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importacionsua',
            name='municipio_alcaldia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importacionsua',
            name='periodo',
            field=models.CharField(max_length=150, verbose_name='Periodo del Reporte'),
        ),
        migrations.AlterField(
            model_name='importacionsua',
            name='prima_rt',
            field=models.TextField(blank=True, null=True, verbose_name='Aportación Patronal / Prima RT'),
        ),
        migrations.AlterField(
            model_name='importacionsua',
            name='subdelegacion_imss',
            field=models.TextField(blank=True, null=True),
        ),
    ]
