# Generated by Django 6.0.2 on 2026-05-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0017_alter_importacionsua_area_geografica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadorsua',
            name='amortizacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='aportacion_patronal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='ausentismos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='baja_clave',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='cred_vivienda',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='fecha_mov_credito',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='incapacidades',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='licencias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='retiro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='suma_infonavit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='tipo_mov_credito',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trabajadorsua',
            name='obrera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Obrera / Cesantía Obr.'),
        ),
        migrations.AlterField(
            model_name='trabajadorsua',
            name='patronal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Patronal / Cesantía Pat.'),
        ),
        migrations.AlterField(
            model_name='trabajadorsua',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal / Suma RCV'),
        ),
    ]
