# Generated by Django 6.0.2 on 2026-05-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0018_trabajadorsua_amortizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadorsua',
            name='total_general',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
