# Generated by Django 6.0.2 on 2026-05-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0019_trabajadorsua_total_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadorsua',
            name='tipo_valor_infonavit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='% o $ o FD'),
        ),
    ]
