# Generated by Django 6.0.2 on 2026-05-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0020_trabajadorsua_tipo_valor_infonavit'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacionsua',
            name='tipo',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('bimestral', 'Bimestral')], default='mensual', max_length=20),
        ),
    ]
