# Generated by Django 6.0.2 on 2026-05-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0021_importacionsua_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadorsua',
            name='cuota_fija',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='excedente_obrera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='excedente_patronal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='gastos_medicos_obrera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='gastos_medicos_patronal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='guarderias_ps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='imss_obrera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='imss_patronal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='imss_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='invalidez_vida_obrera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='invalidez_vida_patronal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='prestaciones_dinero_obrera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='prestaciones_dinero_patronal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trabajadorsua',
            name='riesgo_trabajo_cuota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
