# Generated by Django 6.0.2 on 2026-05-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0022_trabajadorsua_cuota_fija_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='clave',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Clave'),
        ),
    ]
