# Generated by Django 6.0.2 on 2026-05-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0023_contratista_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='clave',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Clave'),
        ),
    ]
