# Generated by Django 6.0.2 on 2026-05-15 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0024_beneficiario_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='beneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.beneficiario', verbose_name='Beneficiario'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='contratista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.contratista', verbose_name='Contratista'),
        ),
    ]
