# Generated by Django 6.0.2 on 2026-05-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0025_empleado_beneficiario_empleado_contratista'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='clave_ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave de Ubicación'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
    ]
