# Generated by Django 6.0.2 on 2026-05-26 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_empresa_modulo_costeos'),
        ('preferencias', '0006_sucursal'),
        ('recursos_humanos', '0027_contratista_regimen_alter_contrato_tipo_contrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=100, verbose_name='Periodo')),
                ('uso_cfdi', models.CharField(default='CN01', max_length=10, verbose_name='Uso de CFDI')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='UUID')),
                ('tipo_nomina', models.CharField(choices=[('O', 'O - Nómina ordinaria'), ('E', 'E - Nómina extraordinaria')], default='O', max_length=1, verbose_name='Tipo de Nómina')),
                ('serie', models.CharField(blank=True, max_length=20, null=True, verbose_name='Serie')),
                ('folio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Folio')),
                ('fecha_emision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Emisión')),
                ('fecha_certificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Certificación')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha Pago')),
                ('fecha_inicial_pago', models.DateField(blank=True, null=True, verbose_name='Fecha Inicial Pago')),
                ('fecha_final_pago', models.DateField(blank=True, null=True, verbose_name='Fecha Final Pago')),
                ('dias_pagados', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Días Pagados')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('curp', models.CharField(max_length=18, verbose_name='CURP')),
                ('nss', models.CharField(max_length=11, verbose_name='NSS')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('rfc_contratista', models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC (Contratista)')),
                ('sdi', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='SDI')),
                ('sbc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='SBC')),
                ('vacaciones_exento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Vacaciones (Exento)')),
                ('vacaciones_dignas_exento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Vacaciones Dignas (Exento)')),
                ('aguinaldo_exento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Aguinaldo (Exento)')),
                ('sueldo_gravado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sueldo (Gravado)')),
                ('vacaciones_gravado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Vacaciones (Gravado)')),
                ('vacaciones_dignas_gravado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Vacaciones Dignas (Gravado)')),
                ('aguinaldo_gravado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Aguinaldo (Gravado)')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominas', to='recursos_humanos.empleado', verbose_name='Empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'ordering': ['-fecha_pago', 'nombre'],
            },
        ),
    ]
