# Generated by Django 6.0.2 on 2026-05-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0028_nomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='antiguedad_sat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Antigüedad (Texto/SAT)'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='periodicidad_pago_sat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Periodicidad Pago (SAT)'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_regimen_sat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Régimen (SAT)'),
        ),
    ]
