# Generated by Django 6.0.2 on 2026-05-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0029_empleado_antiguedad_sat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='jornada_sat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Jornada (SAT)'),
        ),
    ]
