# Generated by Django 6.0.2 on 2026-05-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0030_empleado_jornada_sat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='uso_cfdi',
            field=models.CharField(default='CN01', max_length=255, verbose_name='Uso de CFDI'),
        ),
    ]
