# Generated by Django 6.0.2 on 2026-05-28 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_empresa_modulo_costeos'),
        ('recursos_humanos', '0031_alter_empleado_cp_alter_nomina_uso_cfdi'),
    ]

    operations = [
        migrations.CreateModel(
            name='FielContratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado_cifrado', models.TextField(verbose_name='Certificado (.cer) Cifrado')),
                ('llave_privada_cifrada', models.TextField(verbose_name='Llave Privada (.key) Cifrada')),
                ('rfc_fiel', models.CharField(max_length=13, verbose_name='RFC de la FIEL')),
                ('data_key_cifrada', models.TextField(verbose_name='Data Key Cifrada')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('contratista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiel', to='recursos_humanos.contratista')),
            ],
            options={
                'verbose_name': 'FIEL Contratista',
                'verbose_name_plural': 'FIELs de Contratistas',
            },
        ),
        migrations.CreateModel(
            name='SolicitudDescargaSAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_solicitud', models.CharField(max_length=100, verbose_name='ID de Solicitud SAT')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_comprobante', models.CharField(default='Nomina', max_length=20)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('en_proceso', 'En Proceso'), ('terminada', 'Terminada'), ('error', 'Error'), ('procesada', 'Procesada / Integrada')], default='solicitada', max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('contratista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.contratista')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa')),
            ],
            options={
                'verbose_name': 'Solicitud SAT',
                'verbose_name_plural': 'Solicitudes SAT',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
