# Generated by Django 6.0.2 on 2026-06-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0032_fielcontratista_solicituddescargasat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicituddescargasat',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Solicitud SAT', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='objeto_contrato',
            field=models.TextField(blank=True, null=True, verbose_name='Objeto del Contrato'),
        ),
    ]
