# Generated by Django 6.0.2 on 2026-06-17 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_empresa_estado_servicio'),
        ('recursos_humanos', '0033_alter_solicituddescargasat_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentacionBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(choices=[('REPSE', 'Registro REPSE'), ('SAT', 'Opinión SAT'), ('IMSS', 'Opinión IMSS'), ('INFONAVIT', 'Opinión INFONAVIT'), ('SUA_CEDULA', 'Cédula SUA'), ('SUA_PAGO', 'Pago SUA'), ('LISTA_TRABAJADORES', 'Lista de Trabajadores'), ('OTROS', 'Otros')], max_length=50, verbose_name='Nombre del Documento')),
                ('archivo', models.FileField(upload_to='documentos_beneficiarios/', verbose_name='Archivo')),
                ('mes', models.PositiveIntegerField(verbose_name='Mes (1-12)')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='recursos_humanos.beneficiario', verbose_name='Beneficiario')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Documentación de Beneficiario',
                'verbose_name_plural': 'Documentación de Beneficiarios',
                'unique_together': {('beneficiario', 'nombre_documento', 'mes', 'anio')},
            },
        ),
    ]
