# Generated by Django 5.2.15 on 2026-07-06 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0035_alter_beneficiario_id_alter_contratista_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Acceso'),
        ),
    ]
