# Generated by Django 5.2.15 on 2026-07-07 00:16

import django.core.files.storage
import recursos_humanos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0036_beneficiario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacionbeneficiario',
            name='archivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\luism\\gemini-work\\sistema_inventario\\protected_media'), upload_to=recursos_humanos.models.upload_to_beneficiario_doc, verbose_name='Archivo'),
        ),
    ]
