# Generated by Django 5.2.15 on 2026-07-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0037_alter_documentacionbeneficiario_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacionbeneficiario',
            name='estatus',
            field=models.CharField(choices=[('revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='revision', max_length=20, verbose_name='Estatus'),
        ),
    ]
