# Generated by Django 5.2.15 on 2026-07-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0038_documentacionbeneficiario_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado'), ('cerrado', 'Cerrado')], default='vigente', max_length=20, verbose_name='Estado'),
        ),
    ]
