# Generated by Django 5.2.15 on 2026-07-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0039_alter_contrato_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='estado_periodicidad',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('cerrado', 'Cerrado')], default='vigente', max_length=20, verbose_name='Estado de Periodicidad'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='estado_vigencia',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido')], default='vigente', max_length=20, verbose_name='Estado de Vigencia'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='version',
            field=models.CharField(default='1', max_length=20, verbose_name='Versión'),
        ),
    ]
