# Generated by Django 5.2.15 on 2026-07-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0040_contrato_estado_periodicidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='percepciones_detalladas',
            field=models.JSONField(blank=True, default=dict, verbose_name='Detalle de Percepciones SAT'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado_vigencia',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido'), ('cerrado', 'Cerrado')], default='vigente', max_length=20, verbose_name='Estado de Vigencia'),
        ),
    ]
