# Generated by Django 5.2.15 on 2026-07-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0043_beneficiario_creado_por_contratista_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='deducciones_detalladas',
            field=models.JSONField(blank=True, default=dict, verbose_name='Detalle de Deducciones SAT'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='retiros_ahorro_excedido',
            field=models.BooleanField(default=False, verbose_name='Más de 2 retiros de Fondo de Ahorro'),
        ),
    ]
