# Generated by Django 5.2.15 on 2026-08-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0044_nomina_deducciones_detalladas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('cancelado', 'Cancelado')], default='vigente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='solicituddescargasat',
            name='estatus_cfdi',
            field=models.CharField(default='vigente', max_length=20, verbose_name='Estatus CFDI Solicitado'),
        ),
    ]
