# Generated by Django 5.2.15 on 2026-08-27 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_empresa_uma'),
        ('recursos_humanos', '0045_nomina_estado_solicituddescargasat_estatus_cfdi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorRH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clave')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('nombre_razon_social', models.CharField(max_length=200, verbose_name='Nombre / Razón Social')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('calle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Calle')),
                ('num_ext', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Exterior')),
                ('num_int', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Interior')),
                ('colonia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Colonia')),
                ('cp', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Postal')),
                ('municipio_alcaldia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Municipio/Alcaldía')),
                ('domicilio', models.TextField(blank=True, null=True, verbose_name='Domicilio Fiscal')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_rh_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Proveedor (RH)',
                'verbose_name_plural': 'Proveedores (RH)',
                'ordering': ['-creado_en'],
            },
        ),
    ]
