# Generated by Django 5.2.15 on 2026-08-27 16:59

import django.core.files.storage
import django.db.models.deletion
import recursos_humanos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_empresa_uma'),
        ('recursos_humanos', '0046_proveedorrh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorrh',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedor_rh', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Acceso'),
        ),
        migrations.CreateModel(
            name='DocumentacionProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(choices=[('REPSE', 'Registro REPSE'), ('SAT', 'Opinión SAT'), ('IMSS', 'Opinión IMSS'), ('INFONAVIT', 'Opinión INFONAVIT'), ('CONTRATO_COMPLETO', 'Contrato de Servicios'), ('ACTA_CONSTITUTIVA', 'Acta Constitutiva'), ('IDENTIFICACION', 'Identificación Oficial'), ('COMPROBANTE_DOMICILIO', 'Comprobante de Domicilio'), ('OTROS', 'Otros')], max_length=50, verbose_name='Nombre del Documento')),
                ('archivo', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\luism\\gemini-work\\sistema_inventario\\protected_media'), upload_to=recursos_humanos.models.upload_to_proveedor_doc, verbose_name='Archivo')),
                ('mes', models.PositiveIntegerField(verbose_name='Mes (1-12)')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('status', models.CharField(choices=[('revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='revision', max_length=20, verbose_name='Estatus')),
                ('comentario_rechazo', models.TextField(blank=True, null=True, verbose_name='Comentario de Rechazo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='recursos_humanos.proveedorrh', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Documentación de Proveedor',
                'verbose_name_plural': 'Documentación de Proveedores',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
