# Generated by Django 5.2.15 on 2026-08-27 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0047_proveedorrh_usuario_documentacionproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorrh',
            name='contratista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_rh', to='recursos_humanos.contratista', verbose_name='Contratista'),
        ),
    ]
