# Generated by Django 5.2.15 on 2026-08-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0048_proveedorrh_contratista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacionproveedor',
            name='nombre_documento',
            field=models.CharField(choices=[('REPSE_VIGENTE', 'Constancia/registro REPSE vigente'), ('ACTIVIDAD_REPSE', 'Actividad/servicio registrado en REPSE'), ('CONTRATO_PRESTACION', 'Contrato de prestación de servicios especializados'), ('OBJETO_ESPECIFICO', 'Objeto específico del servicio'), ('NUM_TRABAJADORES', 'Número aproximado de trabajadores que participarán'), ('CFDI_PRESTACION', 'CFDI de la prestación del servicio'), ('CFDI_NOMINA', 'CFDI de nómina de trabajadores que prestaron el servicio'), ('XML_NOMINA', 'XML De Nomina'), ('COMPROBANTE_RETENCION_ISR', 'Comprobante del entero de retenciones de ISR'), ('COMPROBANTE_PAGO_IMSS', 'Comprobante de pago de cuotas IMSS'), ('COMPROBANTE_PAGO_INFONAVIT', 'Comprobante de pago de aportaciones INFONAVIT'), ('DECLARACION_IVA', 'Declaración de IVA del contratista'), ('ACUSE_DECLARACION_IVA', 'Acuse de la declaración de IVA'), ('COMPROBANTE_IVA_TRASLADADO', 'Información/comprobante del IVA trasladado y enterado'), ('COMPROBANTE_PAGO_CONTRATISTA', 'Comprobante bancario del pago al contratista'), ('EVIDENCIA_SERVICIO', 'Evidencia de que el servicio efectivamente se realizó'), ('OPINION_SAT', 'Opinión de cumplimiento SAT'), ('OPINION_IMSS', 'Opinión de cumplimiento IMSS'), ('OPINION_INFONAVIT', 'Opinión de cumplimiento INFONAVIT'), ('RECIBO_PAGO_SAT', 'Recibo Bancario De Pago De Contribuciones SAT'), ('SITUACION_FISCAL_SAT', 'Constancia De Situación Fiscal SAT'), ('CEDULA_SUA', 'Cédula De Determinación De Cuotas, Sistema Único De Autodeterminación'), ('CEDULA_OBRERO_PATRONAL', 'Cédula De Determinación De Cuotas Obrero-Patronales, Aportaciones Y Amortizaciones'), ('RESUMEN_LIQUIDACION', 'Resumen De Liquidación'), ('RECIBO_SIPARE', 'Recibo Bancario - Pago Sipare'), ('FORMATO_PAGO_CUOTAS', 'Formato Para Pago De Cuotas Obrero Patronales, Aportaciones Y Amortizaciones'), ('CUOTAS_SUA_FILE', 'Cuotas Obrero Patronales  .SUA'), ('ACUSE_SISUB', 'Acuse De Recibo Electrónico SISUB'), ('ACUSE_ICSOE', 'Acuse De Informativa De Contratos De Servicios U Obras Especializados ICSOE'), ('DECLARACION_ISR_RETENCIONES', 'Declaración Provisional O Definitiva De Impuestos Federales ISR (Retenciones Por Salario)'), ('DECLARACION_IVA_FEDERAL', 'Declaración Provisional O Definitiva De Impuestos Federales IVA'), ('ACUSE_DECLARACION_IVA_FEDERAL', 'Acuse De Recibo Declaración Provisional O Definitiva De Impuestos Federales IVA'), ('ACUSE_DECLARACION_ISR_RETENCIONES', 'Acuse De Recibo Declaración Provisional O Definitiva De Impuestos Federales ISR (Retenciones Por Salario)'), ('PAGOS_CONTRIBUCIONES_IVA', 'Información Registrada De Pagos De Contribuciones Federales IVA'), ('PAGOS_CONTRIBUCIONES_ISR', 'Información Registrada De Pagos De Contribuciones Federales ISR (Retenciones Por Salario)')], max_length=50, verbose_name='Nombre del Documento'),
        ),
    ]
