# Generated by Django 5.2.15 on 2026-08-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0049_alter_documentacionproveedor_nombre_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorrh',
            name='entidad_federativa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Entidad Federativa'),
        ),
        migrations.AddField(
            model_name='proveedorrh',
            name='estado_vigencia',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido')], default='vigente', max_length=20, verbose_name='Estado de Vigencia'),
        ),
        migrations.AddField(
            model_name='proveedorrh',
            name='fecha_vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vigencia'),
        ),
        migrations.AddField(
            model_name='proveedorrh',
            name='numero_stps',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número STPS (REPSE)'),
        ),
        migrations.AddField(
            model_name='proveedorrh',
            name='registro_patronal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registro Patronal'),
        ),
    ]
