# Generated by Django 5.2.15 on 2026-08-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0050_proveedorrh_entidad_federativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorrh',
            name='estatus',
            field=models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido')], default='activo', max_length=20, verbose_name='Estatus'),
        ),
    ]
