# Generated by Django 5.2.15 on 2026-08-31 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0051_proveedorrh_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratistaCorreoSMTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True, verbose_name='Servidor SMTP (Host)')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='Puerto SMTP')),
                ('smtp_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='Usuario SMTP (Correo)')),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contraseña SMTP')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Usar SSL')),
                ('email_remitente', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Remitente')),
                ('nombre_remitente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Remitente')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('contratista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_smtp', to='recursos_humanos.contratista', verbose_name='Contratista')),
            ],
            options={
                'verbose_name': 'Configuración SMTP de Contratista',
                'verbose_name_plural': 'Configuraciones SMTP de Contratistas',
            },
        ),
    ]
