# Generated by Django 5.2.15 on 2026-08-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0052_contratistacorreosmtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratistacorreosmtp',
            name='email_notificacion_1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Destinatario Principal'),
        ),
        migrations.AddField(
            model_name='contratistacorreosmtp',
            name='email_notificacion_2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='CC 1'),
        ),
        migrations.AddField(
            model_name='contratistacorreosmtp',
            name='email_notificacion_3',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='CC 2'),
        ),
    ]
