# Generated by Django 5.2.15 on 2026-09-04 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0053_contratistacorreosmtp_email_notificacion_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratistaRegistroPatronal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_patronal', models.CharField(max_length=50, verbose_name='Registro Patronal Adicional')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_patronales_adicionales', to='recursos_humanos.contratista', verbose_name='Contratista')),
            ],
            options={
                'verbose_name': 'Registro Patronal Adicional de Contratista',
                'verbose_name_plural': 'Registros Patronales Adicionales de Contratistas',
                'unique_together': {('contratista', 'registro_patronal')},
            },
        ),
    ]
