# Generated by Django 5.2.15 on 2026-09-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0054_contratistaregistropatronal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacionproveedor',
            name='nombre_documento',
            field=models.CharField(choices=[('REPSE_VIGENTE', 'Constancia/registro REPSE vigente (PDF)'), ('CONTRATO_PRESTACION', 'Contrato de prestación de servicios especializados (PDF)'), ('REPORTE_TRABAJADORES', 'Reporte de trabajadores asignados al servicio especializado (EXCEL)'), ('XML_NOMINA_COLABORADORES', 'XML De Nomina de colaboradores asignados (ZIP)'), ('RECIBO_NOMINA_COLABORADORES', 'Recibo de Nomina de colaboradores asignados (ZIP)'), ('OPINION_SAT', 'Opinión de cumplimiento SAT (PDF)'), ('OPINION_IMSS', 'Opinión de cumplimiento IMSS (PDF)'), ('OPINION_INFONAVIT', 'Opinión de cumplimiento INFONAVIT (PDF)'), ('SITUACION_FISCAL_SAT', 'Constancia De Situación Fiscal SAT (PDF)'), ('CEDULA_CUOTAS_MENSUALES', 'Cédula De Cuotas Sociales Mensuales (PDF)'), ('CEDULA_CUOTAS_BIMESTRALES', 'Cédula De Cuotas Sociales Bimestrales (PDF)'), ('RESUMEN_LIQUIDACION', 'Resumen De Liquidación (PDF)'), ('PAGO_SIPARE_MENSUAL', 'Comprobante de pago SIPARE Mensual (PDF)'), ('ACUSE_SISUB_CUATRIMESTRAL', 'Acuse de Presentación Informativa cuatrimestral SISUB (PDF)'), ('ACUSE_ICSOE_CUATRIMESTRAL', 'Acuse de Presentación Informativa cuatrimestral ICSOE (PDF)'), ('DECLARACION_ISR_RETENCIONES', 'Detalle De Declaración Provisional O Definitiva De Impuestos Federales ISR (Retenciones Por Salario) (PDF)'), ('DECLARACION_IVA_DEFINITIVA', 'Detalle De Declaración Definitiva De Impuestos Federales IVA (PDF)'), ('ACUSE_DECLARACION_IVA_DEFINITIVA', 'Acuse De Recibo Declaración Definitiva De Impuestos Federales IVA (PDF)'), ('ACUSE_DECLARACION_ISR_RETENCIONES', 'Acuse De Recibo Declaración Provisional O Definitiva De Impuestos Federales ISR (Retenciones Por Salario) (PDF)'), ('ACUSE_PAGO_IVA', 'Acuse de Pagos De Contribuciones Federales IVA (PDF)'), ('ACUSE_PAGO_ISR', 'Acuse De Pagos De Contribuciones Federales ISR (Retenciones Por Salario) (PDF)'), ('EVIDENCIA_SERVICIO_FOTOS', 'Evidencia del servicio especializado realizado Fotos Jpg (ZIP)')], max_length=60, verbose_name='Nombre del Documento'),
        ),
    ]
