# Generated by Django 6.0.2 on 2026-05-21 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0006_empresa_modulo_recursos_humanos'),
        ('preferencias', '0006_sucursal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Costeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_identificador', models.CharField(max_length=255, verbose_name='Nombre de Producto/Servicio')),
                ('es_manufactura', models.BooleanField(default=False, verbose_name='Manufactura')),
                ('es_comercio', models.BooleanField(default=False, verbose_name='Comercio')),
                ('es_servicio', models.BooleanField(default=False, verbose_name='Servicios')),
                ('margen_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Margen %')),
                ('precio_venta_fijo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio Venta Fijo')),
                ('utiliza_porcentaje', models.BooleanField(default=True, verbose_name='Utiliza Porcentaje')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='IVA %')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.sucursal', verbose_name='Sucursal')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Costeo',
                'verbose_name_plural': 'Costeos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ComercioAdquisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preferencias.moneda')),
                ('costeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_adquisicion', to='costeos.costeo')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturaGastoIndirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_indirectos', to='costeos.costeo')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preferencias.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturaManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_hora', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mano_obra', to='costeos.costeo')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preferencias.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturaMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_primas', to='costeos.costeo')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preferencias.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_servicio', to='costeos.costeo')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preferencias.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=200)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tarifa_hora', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_servicio', to='costeos.costeo')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preferencias.moneda')),
            ],
        ),
    ]
