# Generated by Django 6.0.2 on 2026-05-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costeo',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20, verbose_name='Estado'),
        ),
    ]
