# Generated by Django 6.0.2 on 2026-05-21 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeos', '0002_costeo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='costeo',
            name='duplicado_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicados', to='costeos.costeo'),
        ),
    ]
