# Generated by Django 6.0.2 on 2026-03-17 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0004_alter_categoria_empresa'),
        ('panel', '0001_initial'),
        ('pedidos', '0004_detallepedido_parent_line'),
        ('ventas', '0002_venta_almacen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('fecha_surtido', models.DateTimeField(blank=True, null=True, verbose_name='Surtido el')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('surtido', 'Surtido'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('direccion_envio', models.TextField(blank=True, verbose_name='Dirección de Envío')),
                ('contacto_envio', models.CharField(blank=True, max_length=100, verbose_name='Contacto / Email')),
                ('notas_envio', models.TextField(blank=True, verbose_name='Notas de Paquetería')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
                ('pedido_origen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orden_venta', to='pedidos.pedido', verbose_name='Pedido de Origen')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto')),
                ('orden_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.ordenventa')),
            ],
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
