# Generated by Django 6.0.2 on 2026-03-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_ordenventa_detalleordenventa_delete_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='guia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Guía'),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='quien_recibe',
            field=models.CharField(blank=True, max_length=150, verbose_name='Quién Recibe'),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='telefono_recibe',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono Recibe'),
        ),
    ]
