# Generated by Django 6.0.2 on 2026-04-01 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0005_kardex_lote_kardex_serie'),
        ('ventas', '0004_ordenventa_guia_ordenventa_quien_recibe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almacenes.almacen', verbose_name='Almacén de Salida'),
        ),
    ]
