# Generated by Django 6.0.2 on 2026-04-07 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_contacto'),
        ('ventas', '0005_ordenventa_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenventa',
            name='pedido_origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_venta', to='pedidos.pedido', verbose_name='Pedido de Origen'),
        ),
    ]
