# Generated by Django 6.0.2 on 2026-04-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_ordenventa_pedido_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='estado_entrega',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('listo', 'Listo para enviar'), ('transito', 'En tránsito'), ('entregado', 'Entregado')], default='pendiente', max_length=20, verbose_name='Estado de Entrega'),
        ),
    ]
