# Generated by Django 6.0.2 on 2026-04-14 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_contacto'),
        ('ventas', '0007_ordenventa_estado_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='parent_orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijas', to='ventas.ordenventa'),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='secuencia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordenventa',
            name='pedido_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_venta', to='pedidos.pedido', verbose_name='Pedido de Origen'),
        ),
    ]
