# Generated by Django 5.2.15 on 2026-06-29 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_alter_empresa_id_alter_empresa_logo'),
        ('preferencias', '0008_sucursal_cliente_defecto'),
        ('tesoreria', '0009_alter_cajabanco_id_alter_egreso_id_alter_ingreso_id_and_more'),
        ('ventas', '0010_alter_detalleordenventa_id_alter_ordenventa_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaPOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Caja')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='cerrada', max_length=20, verbose_name='Estado')),
                ('banco_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_pos_tarjeta', to='tesoreria.cajabanco', verbose_name='Banco Tarjeta')),
                ('banco_transferencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_pos_transferencia', to='tesoreria.cajabanco', verbose_name='Banco Transferencias')),
                ('caja_efectivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_pos_efectivo', to='tesoreria.cajabanco', verbose_name='Caja (Efectivo)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.sucursal', verbose_name='Sucursal')),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_pos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado')),
            ],
            options={
                'verbose_name': 'Caja POS',
                'verbose_name_plural': 'Cajas POS',
            },
        ),
        migrations.CreateModel(
            name='SesionCajaPOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Inicial (Efectivo)')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('monto_final_efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Final Efectivo (Contado)')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20, verbose_name='Estado')),
                ('total_ventas_efectivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Ventas Efectivo')),
                ('total_ventas_tarjeta', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Ventas Tarjeta')),
                ('total_ventas_transferencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Ventas Transferencia')),
                ('caja_pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='ventas.cajapos', verbose_name='Caja POS')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_pos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de Caja POS',
                'verbose_name_plural': 'Sesiones de Caja POS',
            },
        ),
    ]
