# Generated by Django 5.2.15 on 2026-07-08 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_empresa_modulo_pos'),
        ('ventas', '0012_detalleordenventa_modificadores_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorteZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Negocio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Ventas Efectivo')),
                ('total_tarjeta', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Ventas Tarjeta')),
                ('total_transferencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Ventas Transferencia')),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Ventas General')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Fondo Inicial')),
                ('monto_final_efectivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Efectivo Real')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Corte Z',
                'verbose_name_plural': 'Cortes Z',
                'unique_together': {('empresa', 'fecha')},
            },
        ),
        migrations.AddField(
            model_name='sesioncajapos',
            name='corte_z',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_corte', to='ventas.cortez', verbose_name='Corte Z'),
        ),
    ]
