# Generated by Django 5.2.15 on 2026-07-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_cortez_sesioncajapos_corte_z'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioncajapos',
            name='total_ventas_credito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Ventas Crédito'),
        ),
        migrations.AlterField(
            model_name='ordenventa',
            name='estado_entrega',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('listo', 'Listo para enviar'), ('transito', 'En tránsito'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado de Entrega'),
        ),
    ]
