# Generated by Django 5.2.15 on 2026-07-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_sesioncajapos_total_ventas_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortez',
            name='total_credito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Ventas Crédito'),
        ),
    ]
