# Generated by Django 6.0.2 on 2026-03-07 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('recepciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerecepcion',
            name='detalle_compra',
            field=models.ForeignKey(blank=True, help_text='Indica a qué línea específica de la orden de compra corresponde este ingreso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_asociadas', to='compras.detallecompra', verbose_name='Partida de Orden de Compra'),
        ),
    ]
