# Generated by Django 6.0.2 on 2026-03-09 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepciones', '0002_detallerecepcion_detalle_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRecepcionExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('lote', 'Lote'), ('serie', 'Serie')], max_length=10)),
                ('lote', models.CharField(blank=True, help_text='Nombre o número del lote', max_length=50, null=True)),
                ('cantidad_lote', models.PositiveIntegerField(default=0, help_text='Cantidad de piezas en este lote')),
                ('serie', models.CharField(blank=True, help_text='Número de serie único', max_length=100, null=True)),
                ('detalle_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='recepciones.detallerecepcion')),
            ],
        ),
    ]
