# Generated by Django 6.0.2 on 2026-03-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepciones', '0003_detallerecepcionextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='aduana',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aduana'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='fecha_pedimento',
            field=models.DateField(blank=True, help_text='Fecha del documento de aduana', null=True, verbose_name='Fecha Pedimento'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='pedimento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pedimento'),
        ),
    ]
