# Generated by Django 6.0.2 on 2026-03-11 00:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepciones', '0004_recepcion_aduana_recepcion_fecha_pedimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='importe_aduana',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo total de impuestos/aduana', max_digits=12, verbose_name='Importación Aduanal'),
        ),
    ]
