# Generated by Django 6.0.2 on 2026-03-13 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
        ('recepciones', '0005_recepcion_importe_aduana'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa'),
        ),
    ]
