# Generated by Django 6.0.2 on 2026-03-16 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_ordencompra_solicitud_origen'),
        ('recepciones', '0006_recepcion_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerecepcion',
            name='detalle_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_asociadas', to='compras.detallecompra', verbose_name='Partida de Orden de Compra'),
        ),
    ]
