# Generated by Django 6.0.2 on 2026-03-30 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferencias', '0001_initial'),
        ('recepciones', '0007_alter_detallerecepcion_detalle_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.moneda', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Tipo de Cambio'),
        ),
        migrations.AlterField(
            model_name='detallerecepcionextra',
            name='cantidad_lote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallerecepcionextra',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detallerecepcionextra',
            name='serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
