# Generated by Django 6.0.2 on 2026-04-01 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0005_kardex_lote_kardex_serie'),
        ('recepciones', '0008_recepcion_moneda_recepcion_tipo_cambio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerecepcionextra',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_extra', to='almacenes.almacen'),
        ),
    ]
