# Generated by Django 6.0.2 on 2026-04-22 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_producto_test_calidad'),
        ('recepciones', '0009_detallerecepcionextra_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerecepcionextra',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras_trazabilidad', to='core.producto'),
        ),
        migrations.AlterField(
            model_name='detallerecepcionextra',
            name='detalle_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='recepciones.detallerecepcion'),
        ),
    ]
