# Generated by Django 6.0.2 on 2026-04-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepciones', '0010_detallerecepcionextra_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerecepcionextra',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
