# Generated by Django 6.0.2 on 2026-05-12 22:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepciones', '0012_recepcion_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='fecha_comprobante',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Comprobante'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='factura',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Folio de Comprobantes'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Recepción'),
        ),
    ]
