# Generated by Django 5.2.15 on 2026-07-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepciones', '0014_alter_detallerecepcion_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerecepcionextra',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Caducidad'),
        ),
        migrations.AlterField(
            model_name='detallerecepcionextra',
            name='tipo',
            field=models.CharField(choices=[('lote', 'Lote'), ('serie', 'Serie'), ('caducidad', 'Caducidad')], max_length=15),
        ),
    ]
