# Generated by Django 6.0.2 on 2026-03-14 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0004_alter_categoria_empresa'),
        ('panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotizacion_origen_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Cotización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado el')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('pendiente', 'Pendiente'), ('completo', 'Completo'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa (Tenant)')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField(default=1, verbose_name='Cant. Solicitada')),
                ('cantidad_entregada', models.PositiveIntegerField(default=0, verbose_name='Cant. Entregada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('estado_linea', models.CharField(choices=[('pendiente', 'Pendiente'), ('reservado', 'Reservado'), ('compra', 'Compra'), ('produccion', 'Producción'), ('parcial', 'Parcial'), ('completo', 'Completo')], default='pendiente', max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
            ],
        ),
    ]
