# Generated by Django 6.0.2 on 2026-03-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En Revisión'), ('confirmado', 'Confirmado'), ('pendiente', 'Pendiente'), ('completo', 'Completo'), ('cancelado', 'Cancelado')], default='borrador', max_length=20),
        ),
    ]
