# Generated by Django 6.0.2 on 2026-03-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='estado_linea',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('reservado', 'Reservado'), ('en_proceso', 'Aprobación'), ('comprado', 'Comprado'), ('compra', 'Compra'), ('produccion', 'Producción'), ('parcial', 'Parcial'), ('completo', 'Completo')], default='pendiente', max_length=20),
        ),
    ]
