# Generated by Django 6.0.2 on 2026-03-16 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_detallepedido_estado_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='parent_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas_hijas', to='pedidos.detallepedido', verbose_name='Partida Original (Si fue dividida)'),
        ),
    ]
