# Generated by Django 6.0.2 on 2026-03-24 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_envio_calle_cliente_envio_colonia_and_more'),
        ('pedidos', '0004_detallepedido_parent_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to='clientes.contactocliente', verbose_name='Contacto Asignado'),
        ),
    ]
