# Generated by Django 6.0.2 on 2026-05-11 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_contacto'),
        ('preferencias', '0006_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.sucursal', verbose_name='Sucursal'),
        ),
    ]
