# Generated by Django 5.2.15 on 2026-06-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_detallepedido_id_alter_pedido_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='aplica_iva',
            field=models.BooleanField(default=True, verbose_name='Aplica IVA'),
        ),
    ]
