# Generated by Django 5.2.15 on 2026-06-29 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedido_aplica_iva'),
        ('ventas', '0011_cajapos_sesioncajapos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='sesion_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='ventas.sesioncajapos', verbose_name='Sesión de Caja POS'),
        ),
    ]
