# Generated by Django 5.2.15 on 2026-07-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_pedido_sesion_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='modificadores_json',
            field=models.TextField(blank=True, null=True, verbose_name='Modificadores Seleccionados'),
        ),
    ]
