# Generated by Django 6.0.2 on 2026-04-29 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0003_empresa_calle_empresa_colonia_empresa_cp_and_more'),
        ('preferencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('caja', 'Caja'), ('banco', 'Banco')], default='caja', max_length=10, verbose_name='Tipo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Caja/Banco')),
                ('banco_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Banco')),
                ('cuenta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cuenta')),
                ('clabe', models.CharField(blank=True, max_length=18, null=True, verbose_name='CLABE Interbancaria')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preferencias.moneda', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Caja o Banco',
                'verbose_name_plural': 'Cajas y Bancos',
                'ordering': ['nombre'],
            },
        ),
    ]
