# Generated by Django 6.0.2 on 2026-04-29 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_empresa_calle_empresa_colonia_empresa_cp_and_more'),
        ('pedidos', '0005_pedido_contacto'),
        ('preferencias', '0001_initial'),
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia'), ('compensacion', 'Compensación')], max_length=20, verbose_name='Forma de Pago')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia')),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Tipo de Cambio')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (Abono)')),
                ('monto_mxn', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto en MXN')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('caja_banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cajabanco', verbose_name='Caja/Banco')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preferencias.moneda', verbose_name='Moneda')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Pago de Pedido',
                'verbose_name_plural': 'Pagos de Pedidos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
