# Generated by Django 6.0.2 on 2026-04-29 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_empresa_calle_empresa_colonia_empresa_cp_and_more'),
        ('preferencias', '0001_initial'),
        ('tesoreria', '0002_pagopedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Tipo de Cambio')),
                ('monto_mxn', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto MXN')),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia'), ('compensacion', 'Compensación')], max_length=20, verbose_name='Forma de Pago')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('caja_banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cajabanco', verbose_name='Caja/Banco')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preferencias.moneda', verbose_name='Moneda')),
                ('pago_pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingreso_vinc', to='tesoreria.pagopedido')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
