# Generated by Django 6.0.2 on 2026-04-29 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_ordencompra_sucursal'),
        ('panel', '0003_empresa_calle_empresa_colonia_empresa_cp_and_more'),
        ('preferencias', '0001_initial'),
        ('tesoreria', '0004_ingreso_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia'), ('compensacion', 'Compensación')], max_length=20, verbose_name='Forma de Pago')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia')),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Tipo de Cambio')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (Abono)')),
                ('monto_mxn', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto en MXN')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('caja_banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cajabanco', verbose_name='Caja/Banco')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preferencias.moneda', verbose_name='Moneda')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='compras.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Pago de Compra',
                'verbose_name_plural': 'Pagos de Compras',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Tipo de Cambio')),
                ('monto_mxn', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto MXN')),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia'), ('compensacion', 'Compensación')], max_length=20, verbose_name='Forma de Pago')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia')),
                ('estado', models.CharField(choices=[('aplicado', 'Aplicado'), ('cancelado', 'Cancelado')], default='aplicado', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('caja_banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cajabanco', verbose_name='Caja/Banco')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preferencias.moneda', verbose_name='Moneda')),
                ('pago_compra', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egreso_vinc', to='tesoreria.pagocompra')),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
