# Generated by Django 6.0.2 on 2026-04-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0005_pagocompra_egreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocompra',
            name='estado',
            field=models.CharField(choices=[('aplicado', 'Aplicado'), ('cancelado', 'Cancelado')], default='aplicado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='pagopedido',
            name='estado',
            field=models.CharField(choices=[('aplicado', 'Aplicado'), ('cancelado', 'Cancelado')], default='aplicado', max_length=20, verbose_name='Estado'),
        ),
    ]
