# Generated by Django 6.0.2 on 2026-05-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0006_pagocompra_estado_pagopedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelación'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelación'),
        ),
        migrations.AddField(
            model_name='pagocompra',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelación'),
        ),
        migrations.AddField(
            model_name='pagopedido',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelación'),
        ),
    ]
