# Generated by Django 6.0.2 on 2026-05-11 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferencias', '0006_sucursal'),
        ('tesoreria', '0007_egreso_motivo_cancelacion_ingreso_motivo_cancelacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajabanco',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='pagocompra',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='pagopedido',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.sucursal', verbose_name='Sucursal'),
        ),
    ]
