# Generated by Django 5.2.15 on 2026-07-30 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0009_alter_cajabanco_id_alter_egreso_id_alter_ingreso_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia'), ('compensacion', 'Compensación'), ('credito', 'Crédito')], max_length=20, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='caja_banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cajabanco', verbose_name='Caja/Banco'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia'), ('compensacion', 'Compensación'), ('credito', 'Crédito')], max_length=20, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='pagocompra',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia'), ('compensacion', 'Compensación'), ('credito', 'Crédito')], max_length=20, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='pagopedido',
            name='caja_banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cajabanco', verbose_name='Caja/Banco'),
        ),
        migrations.AlterField(
            model_name='pagopedido',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='pagopedido',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia'), ('compensacion', 'Compensación'), ('credito', 'Crédito')], max_length=20, verbose_name='Forma de Pago'),
        ),
    ]
