# Generated by Django 6.0.2 on 2026-05-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferencias', '0003_permiso_rol_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisorolaccion',
            name='area',
            field=models.CharField(choices=[('ventas', 'Ventas'), ('compras', 'Compras'), ('produccion', 'Producción'), ('inventario', 'Inventario')], default='ventas', max_length=40),
        ),
        migrations.AlterField(
            model_name='permisorolmodulo',
            name='modulo',
            field=models.CharField(choices=[('ventas', 'Ventas'), ('produccion', 'Producción')], default='ventas', max_length=40),
        ),
    ]
