# Generated by Django 6.0.2 on 2026-05-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferencias', '0004_alter_permisorolaccion_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisorolaccion',
            name='area',
            field=models.CharField(choices=[('ventas', 'Ventas'), ('compras', 'Compras'), ('produccion', 'Producción'), ('inventario', 'Inventario'), ('tesoreria', 'Tesorería')], default='ventas', max_length=40),
        ),
    ]
