# Generated by Django 6.0.2 on 2026-05-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_empresa_modulo_recursos_humanos'),
        ('preferencias', '0005_alter_permisorolaccion_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Sucursal')),
                ('calle', models.CharField(max_length=200, verbose_name='Calle')),
                ('numero_exterior', models.CharField(max_length=50, verbose_name='Número Exterior')),
                ('numero_interior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Interior')),
                ('colonia', models.CharField(max_length=150, verbose_name='Colonia')),
                ('ciudad', models.CharField(max_length=150, verbose_name='Ciudad/Municipio')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('pais', models.CharField(default='México', max_length=100, verbose_name='País')),
                ('cp', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='panel.empresa')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
    ]
