# Generated by Django 5.2.15 on 2026-06-29 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_id_alter_contactocliente_id'),
        ('preferencias', '0007_alter_asignacionrolusuario_id_alter_moneda_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='cliente_defecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales_defecto', to='clientes.cliente', verbose_name='Cliente por Defecto (POS)'),
        ),
    ]
