# Generated by Django 5.2.15 on 2026-07-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferencias', '0008_sucursal_cliente_defecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisorolaccion',
            name='area',
            field=models.CharField(choices=[('ventas', 'Ventas'), ('compras', 'Compras'), ('produccion', 'Producción'), ('inventario', 'Inventario'), ('tesoreria', 'Tesorería'), ('recursos_humanos', 'Recursos Humanos')], default='ventas', max_length=40),
        ),
    ]
