# Generated by Django 5.2.15 on 2026-08-31 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferencias', '0011_alter_permisorolaccion_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCorreoSMTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True, verbose_name='Servidor SMTP (Host)')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='Puerto SMTP')),
                ('smtp_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='Usuario SMTP (Correo)')),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contraseña SMTP')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Usar SSL')),
                ('email_remitente', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Remitente')),
                ('nombre_remitente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Remitente')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_smtp', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Configuración SMTP de Usuario',
                'verbose_name_plural': 'Configuraciones SMTP de Usuarios',
            },
        ),
    ]
