# Generated by Django 6.0.2 on 2026-03-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Empresa')),
                ('subdominio', models.SlugField(help_text='Ej: mizona.crossoversuite.com', max_length=100, unique=True, verbose_name='Subdominio (URL)')),
                ('usuario_admin', models.CharField(max_length=50, verbose_name='Usuario Admin de la Empresa')),
                ('correo_contacto', models.EmailField(max_length=254, verbose_name='Correo de contacto')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('activa', models.BooleanField(default=True, verbose_name='Empresa Activa')),
            ],
            options={
                'verbose_name': 'Empresa (Tenant)',
                'verbose_name_plural': 'Empresas (Tenants)',
            },
        ),
    ]
