# Generated by Django 6.0.2 on 2026-04-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo de la empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de contacto'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de contacto'),
        ),
    ]
