# Generated by Django 6.0.2 on 2026-04-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_empresa_logo_empresa_nombre_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='calle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='colonia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número'),
        ),
    ]
