# Generated by Django 6.0.2 on 2026-05-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_empresa_calle_empresa_colonia_empresa_cp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='modulo_compras',
            field=models.BooleanField(default=True, verbose_name='Módulo Compras'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulo_inventarios',
            field=models.BooleanField(default=True, verbose_name='Módulo Inventarios'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulo_produccion',
            field=models.BooleanField(default=True, verbose_name='Módulo Producción'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulo_tesoreria',
            field=models.BooleanField(default=True, verbose_name='Módulo Tesorería'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulo_ventas',
            field=models.BooleanField(default=True, verbose_name='Módulo Ventas'),
        ),
    ]
