# Generated by Django 6.0.2 on 2026-05-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_empresa_modulo_compras_empresa_modulo_inventarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fecha_inicio_licencia',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de Licencia'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_vencimiento_licencia',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento de Licencia'),
        ),
    ]
