# Generated by Django 6.0.2 on 2026-05-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_empresa_fecha_inicio_licencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='modulo_recursos_humanos',
            field=models.BooleanField(default=True, verbose_name='Módulo Recursos Humanos'),
        ),
    ]
