# Generated by Django 6.0.2 on 2026-05-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_empresa_modulo_recursos_humanos'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='modulo_costeos',
            field=models.BooleanField(default=True, verbose_name='Módulo Costeos'),
        ),
    ]
