# Generated by Django 6.0.2 on 2026-06-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_empresa_modulo_costeos'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='limite_contratistas',
            field=models.PositiveIntegerField(default=10, verbose_name='Límite de Contratistas'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='limite_espacio_disco',
            field=models.PositiveIntegerField(default=1024, help_text='En Megabytes', verbose_name='Límite de Espacio (MB)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='limite_sucursales',
            field=models.PositiveIntegerField(default=5, verbose_name='Límite de Sucursales'),
        ),
    ]
