# Generated by Django 6.0.2 on 2026-06-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_empresa_limite_contratistas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='estado_servicio',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('suspendida', 'Suspendida')], default='activa', max_length=20, verbose_name='Estado del Servicio'),
        ),
    ]
