# Generated by Django 5.2.15 on 2026-06-25 17:04

import panel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_empresa_estado_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=panel.models.upload_to_empresa_logo, verbose_name='Logo de la empresa'),
        ),
    ]
