# Generated by Django 5.2.15 on 2026-07-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_alter_empresa_id_alter_empresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='modulo_pos',
            field=models.BooleanField(default=True, verbose_name='Módulo POS'),
        ),
    ]
