# Generated by Django 5.2.15 on 2026-07-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_empresa_modulo_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='uma',
            field=models.DecimalField(decimal_places=2, default=117.31, max_digits=10, verbose_name='UMA'),
        ),
    ]
