# Generated by Django 6.0.2 on 2026-03-14 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_categoria_empresa'),
        ('panel', '0001_initial'),
        ('pedidos', '0002_alter_pedido_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Solicitud')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Enviada el')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada a Compras'), ('atendida', 'Atendida (OC Generada)'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('notas', models.TextField(blank=True, verbose_name='Notas / Urgencia')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
                ('pedido_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido', verbose_name='Pedido Origen')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSolicitudCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField(verbose_name='Cant. Solicitada')),
                ('detalle_pedido_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.detallepedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='solicitudcompras.solicitudcompra')),
            ],
        ),
    ]
