# Generated by Django 6.0.2 on 2026-03-14 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0003_inventario_reservado'),
        ('proveedores', '0001_initial'),
        ('solicitudcompras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicitudcompra',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacenes.almacen', verbose_name='Almacén Destino'),
        ),
        migrations.AddField(
            model_name='detallesolicitudcompra',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Unitario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallesolicitudcompra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor', verbose_name='Proveedor Sugerido'),
        ),
        migrations.AlterField(
            model_name='solicitudcompra',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('aprobada', 'Aprobada'), ('enviada', 'Enviada a Compras'), ('atendida', 'Atendida (OC Generada)'), ('cancelada', 'Cancelada')], default='borrador', max_length=20),
        ),
    ]
