# Generated by Django 6.0.2 on 2026-03-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudcompras', '0002_detallesolicitudcompra_almacen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesolicitudcompra',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Unitario'),
        ),
    ]
