# Generated by Django 6.0.2 on 2026-03-30 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferencias', '0001_initial'),
        ('solicitudcompras', '0003_alter_detallesolicitudcompra_costo_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicitudcompra',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.moneda', verbose_name='Moneda'),
        ),
    ]
