# Generated by Django 6.0.2 on 2026-04-17 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_sucursalproveedor'),
        ('solicitudcompras', '0004_detallesolicitudcompra_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicitudcompra',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.sucursalproveedor', verbose_name='Sucursal'),
        ),
    ]
