# Generated by Django 6.0.2 on 2026-05-10 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_listapreciocosto'),
        ('solicitudcompras', '0005_detallesolicitudcompra_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicitudcompra',
            name='lista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.listapreciocosto', verbose_name='Lista de Costo'),
        ),
    ]
