# Generated by Django 6.0.2 on 2026-05-11 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferencias', '0006_sucursal'),
        ('solicitudcompras', '0006_detallesolicitudcompra_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.sucursal', verbose_name='Sucursal'),
        ),
    ]
