# Generated by Django 5.2.15 on 2026-06-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudcompras', '0008_alter_detallesolicitudcompra_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='aplica_iva',
            field=models.BooleanField(default=True, verbose_name='Aplica IVA'),
        ),
    ]
