# Generated by Django 6.0.2 on 2026-05-09 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_categoria_empresa_subcategoria_empresa'),
        ('panel', '0003_empresa_calle_empresa_colonia_empresa_cp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecioCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Lista')),
                ('porcentaje_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Porcentaje Extra (%)')),
                ('monto_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Extra ($)')),
                ('tipo', models.CharField(choices=[('precio', 'Precio'), ('costo', 'Costo')], default='precio', max_length=10, verbose_name='Tipo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Lista de Precio/Costo',
                'verbose_name_plural': 'Listas de Precios/Costos',
                'ordering': ['nombre'],
            },
        ),
    ]
