# Generated by Django 5.2.15 on 2026-07-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_alter_categoria_id_alter_listapreciocosto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listapreciocosto',
            name='dias_semana',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Días de la semana'),
        ),
        migrations.AddField(
            model_name='listapreciocosto',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Fin'),
        ),
        migrations.AddField(
            model_name='listapreciocosto',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio'),
        ),
    ]
