# Generated by Django 6.0.2 on 2026-03-29 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0003_inventario_reservado'),
        ('core', '0006_producto_ieps_producto_iva'),
        ('panel', '0001_initial'),
        ('pedidos', '0005_pedido_contacto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad a Producir')),
                ('estado', models.CharField(choices=[('pendiente', 'Esperando Materiales'), ('listo', 'Listo para Iniciar'), ('en_proceso', 'En Proceso'), ('terminado', 'Terminado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_terminado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Término')),
                ('notas', models.TextField(blank=True, verbose_name='Notas del Maestro')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacenes.almacen', verbose_name='Almacén / Taller')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa (Tenant)')),
                ('pedido_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_produccion', to='pedidos.pedido', verbose_name='Pedido Origen')),
                ('producto', models.ForeignKey(limit_choices_to={'tipo_abastecimiento': 'produccion'}, on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto a Fabricar')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable del Taller')),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'verbose_name_plural': 'Órdenes de Producción',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
