# Generated by Django 6.0.2 on 2026-03-29 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_producto_ieps_producto_iva'),
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_produccion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que solicitó'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_proceso', 'En Proceso'), ('testeo', 'Testeo / Calidad'), ('terminado', 'Terminado'), ('cancelado', 'Cancelada')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable del Taller'),
        ),
        migrations.CreateModel(
            name='DetalleOrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad Requerida')),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.ordenproduccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto', verbose_name='Componente')),
            ],
        ),
    ]
