# Generated by Django 6.0.2 on 2026-03-29 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
        ('produccion', '0002_ordenproduccion_solicitante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Test')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción / Objetivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Test de Calidad',
                'verbose_name_plural': 'Tests de Calidad',
            },
        ),
        migrations.CreateModel(
            name='ItemTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=255, verbose_name='Tarea a realizar')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='produccion.test')),
            ],
            options={
                'verbose_name': 'Tarea del Test',
                'verbose_name_plural': 'Tareas del Test',
                'ordering': ['orden'],
            },
        ),
    ]
