# Generated by Django 6.0.2 on 2026-03-29 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_test_itemtest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoTestOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False, verbose_name='¿Pasó la prueba?')),
                ('fecha_chequeo', models.DateTimeField(blank=True, null=True)),
                ('item_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.itemtest')),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_test', to='produccion.ordenproduccion')),
                ('usuario_verifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Inspeccionado por')),
            ],
            options={
                'unique_together': {('orden_produccion', 'item_test')},
            },
        ),
    ]
