# Generated by Django 6.0.2 on 2026-04-21 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0006_kardex_usuario'),
        ('clientes', '0002_cliente_envio_calle_cliente_envio_colonia_and_more'),
        ('produccion', '0004_resultadotestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='almacen_materia_prima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_salida', to='almacenes.almacen', verbose_name='Almacén de Salida (MP)'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_entrada', to='almacenes.almacen', verbose_name='Almacén de Entrada (PT)'),
        ),
    ]
