# Generated by Django 6.0.2 on 2026-05-11 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferencias', '0006_sucursal'),
        ('produccion', '0005_ordenproduccion_almacen_materia_prima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.sucursal', verbose_name='Sucursal'),
        ),
    ]
