# Generated by Django 6.0.2 on 2026-03-06 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('calle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Calle')),
                ('numero_ext', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número Exterior')),
                ('numero_int', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número Interior')),
                ('colonia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Colonia')),
                ('estado_dir', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado (Ubicación)')),
                ('cp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado')),
                ('tipo', models.CharField(choices=[('prospecto', 'Prospecto'), ('cliente_nuevo', 'Cliente Nuevo'), ('cliente_activo', 'Cliente Activo'), ('cliente_inactivo', 'Cliente Inactivo'), ('vip', 'VIP')], default='prospecto', max_length=20, verbose_name='Tipo')),
                ('relacion', models.CharField(choices=[('directo', 'Directo'), ('referido', 'Referido'), ('revendedor', 'Revendedor')], default='directo', max_length=20, verbose_name='Relación')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa (Tenant)')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('telefono_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono 1')),
                ('telefono_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono 2')),
                ('correo_1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo 1')),
                ('correo_2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo 2')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
