# Generated by Django 6.0.2 on 2026-03-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='envio_calle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Calle Envío'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='envio_colonia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Colonia Envío'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='envio_correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Recibe'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='envio_cp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CP Envío'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='envio_estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado Envío'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='envio_notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas de Envío'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='envio_numero_ext',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número Ext. Envío'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='envio_numero_int',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número Int. Envío'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='envio_quien_recibe',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Quién Recibe'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='envio_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Recibe'),
        ),
    ]
