# Generated by Django 6.0.2 on 2026-05-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='sucursal',
        ),
    ]
