# Generated by Django 6.0.2 on 2026-05-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='envio_cp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CP Envío'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='envio_numero_ext',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Ext. Envío'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='envio_numero_int',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Int. Envío'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_ext',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Exterior'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_int',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Interior'),
        ),
    ]
