# Generated by Django 5.2.15 on 2026-07-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos'),
        ),
    ]
