# Generated by Django 6.0.2 on 2026-04-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='resultado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('ganada', 'Ganada'), ('perdida', 'Perdida')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('vendida', 'Vendida'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20),
        ),
    ]
