# Generated by Django 6.0.2 on 2026-04-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizacion_resultado_alter_cotizacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('ganada', 'Ganada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20),
        ),
    ]
