# Generated by Django 5.2.15 on 2026-06-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_alter_cotizacion_id_alter_detallecotizacion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='aplica_iva',
            field=models.BooleanField(default=True, verbose_name='Aplica IVA'),
        ),
    ]
