# Generated by Django 6.0.2 on 2026-03-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_ordencompra_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('aprobada', 'Aprobada'), ('recibida', 'Recibida'), ('parcial', 'Parcial'), ('cancelada', 'Cancelada')], default='borrador', max_length=20),
        ),
    ]
