# Generated by Django 6.0.2 on 2026-03-13 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_ordencompra_estado'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(limit_choices_to={'estado': 'activo'}, on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
    ]
