# Generated by Django 6.0.2 on 2026-03-14 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_ordencompra_proveedor'),
        ('solicitudcompras', '0003_alter_detallesolicitudcompra_costo_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='solicitud_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_generadas', to='solicitudcompras.solicitudcompra', verbose_name='Solicitud de Compra Origen'),
        ),
    ]
