# Generated by Django 6.0.2 on 2026-03-29 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_ordencompra_solicitud_origen'),
        ('pedidos', '0005_pedido_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='detalle_pedido_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.detallepedido', verbose_name='Partida de Pedido Origen'),
        ),
    ]
