# Generated by Django 6.0.2 on 2026-03-30 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_detallecompra_detalle_pedido_origen'),
        ('preferencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.moneda', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Tipo de Cambio'),
        ),
    ]
