# Generated by Django 6.0.2 on 2026-04-17 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_ordencompra_moneda_ordencompra_tipo_cambio'),
        ('proveedores', '0002_sucursalproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.sucursalproveedor', verbose_name='Sucursal'),
        ),
    ]
