# Generated by Django 6.0.2 on 2026-05-11 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_ordencompra_sucursal'),
        ('preferencias', '0006_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='sucursal_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferencias.sucursal', verbose_name='Sucursal Empresa'),
        ),
    ]
