# Generated by Django 6.0.2 on 2026-05-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_ordencompra_sucursal_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Descuento'),
        ),
    ]
