# Generated by Django 5.2.15 on 2026-06-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_alter_detallecompra_id_alter_ordencompra_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='aplica_iva',
            field=models.BooleanField(default=True, verbose_name='Aplica IVA'),
        ),
    ]
