# Generated by Django 6.0.2 on 2026-03-06 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Almacén')),
                ('responsable', models.CharField(blank=True, max_length=150, null=True, verbose_name='Responsable')),
                ('calle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Calle')),
                ('numero_ext', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Exterior')),
                ('numero_int', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Interior')),
                ('colonia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Colonia')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('cp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad Física')),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Promedio')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='almacenes.almacen')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Stock en Almacén',
                'verbose_name_plural': 'Stocks en Almacenes',
            },
        ),
    ]
