# Generated by Django 6.0.2 on 2026-03-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='reservado',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Reservada en Pedidos'),
        ),
    ]
