# Generated by Django 6.0.2 on 2026-04-01 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0003_inventario_reservado'),
        ('core', '0007_producto_test_calidad'),
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(blank=True, help_text='Ej: REC-0001, OV-0005, Ajuste manual', max_length=200, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_kardex', to='almacenes.almacen')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_kardex', to='core.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Kardex',
                'verbose_name_plural': 'Movimientos de Kardex',
                'ordering': ['-fecha'],
            },
        ),
    ]
