# Generated by Django 6.0.2 on 2026-04-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0004_kardex'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='kardex',
            name='serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Núm. Serie'),
        ),
    ]
