# Generated by Django 5.2.15 on 2026-06-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0007_almacen_sucursal_inventario_sucursal_kardex_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
