# Generated by Django 6.0.2 on 2026-03-06 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='RFC')),
                ('cp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('domicilio', models.TextField(blank=True, null=True, verbose_name='Domicilio Fiscal')),
                ('contacto_nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Contacto')),
                ('contacto_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('contacto_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['-creado_en'],
            },
        ),
    ]
