# Generated by Django 6.0.2 on 2026-05-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_sucursalproveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Postal'),
        ),
    ]
