# Generated by Django 6.0.2 on 2026-06-09 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_transaccion_extras_data_transaccion_lote_and_more'),
        ('panel', '0007_empresa_modulo_costeos'),
        ('proveedores', '0003_alter_proveedor_cp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapeoProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_proveedor', models.CharField(max_length=100, verbose_name='Clave en Factura del Proveedor')),
                ('descripcion_proveedor', models.TextField(blank=True, null=True, verbose_name='Descripción en Factura')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.empresa', verbose_name='Empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos_proveedores', to='core.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos_productos', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Mapeo de Producto',
                'verbose_name_plural': 'Mapeos de Productos',
                'unique_together': {('empresa', 'proveedor', 'clave_proveedor')},
            },
        ),
    ]
