name: Deploy to VPS

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: srv1254281.hstgr.cloud
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/django/sistema_inventario
            git fetch origin
            git reset --hard origin/main
            /var/www/django/sistema_inventario/venv/bin/pip install -r requirements.txt
            /var/www/django/sistema_inventario/venv/bin/python manage.py migrate --noinput
            /var/www/django/sistema_inventario/venv/bin/python manage.py collectstatic --clear --noinput
            sudo systemctl restart gunicorn-sistema
            sudo systemctl reload nginx